class_name Palette
## Aren32 -- https://lospec.com/palette-list/aren32
##
## GENERATED by tools/gen_palette.py from assets/palette/aren32.hex.
## Do not edit by hand; edit the .hex and re-run the generator.
##
## Every colour drawn in code comes from here. Sticking to one palette is
## what makes hand-drawn art and downloaded assets look like one game.

const COLORS: Array[Color] = [
	Color(0.101961, 0.082353, 0.086275),  #  0  #1a1516
	Color(0.129412, 0.094118, 0.105882),  #  1  #21181b
	Color(0.172549, 0.12549, 0.145098),  #  2  #2c2025
	Color(0.239216, 0.160784, 0.211765),  #  3  #3d2936
	Color(0.321569, 0.2, 0.247059),  #  4  #52333f
	Color(0.560784, 0.301961, 0.341176),  #  5  #8f4d57
	Color(0.741176, 0.415686, 0.384314),  #  6  #bd6a62
	Color(1.0, 0.682353, 0.439216),  #  7  #ffae70
	Color(1.0, 0.807843, 0.568627),  #  8  #ffce91
	Color(0.996078, 0.654902, 0.654902),  #  9  #fea7a7
	Color(0.270588, 0.113725, 0.258824),  # 10  #451d42
	Color(0.380392, 0.117647, 0.290196),  # 11  #611e4a
	Color(0.505882, 0.12549, 0.309804),  # 12  #81204f
	Color(0.678431, 0.184314, 0.270588),  # 13  #ad2f45
	Color(0.870588, 0.321569, 0.243137),  # 14  #de523e
	Color(0.901961, 0.470588, 0.223529),  # 15  #e67839
	Color(0.941176, 0.709804, 0.254902),  # 16  #f0b541
	Color(1.0, 0.933333, 0.513725),  # 17  #ffee83
	Color(0.784314, 0.831373, 0.364706),  # 18  #c8d45d
	Color(0.643137, 0.768627, 0.262745),  # 19  #a4c443
	Color(0.388235, 0.670588, 0.247059),  # 20  #63ab3f
	Color(0.231373, 0.490196, 0.309804),  # 21  #3b7d4f
	Color(0.137255, 0.231373, 0.211765),  # 22  #233b36
	Color(0.164706, 0.34902, 0.309804),  # 23  #2a594f
	Color(0.211765, 0.529412, 0.509804),  # 24  #368782
	Color(0.309804, 0.643137, 0.721569),  # 25  #4fa4b8
	Color(0.572549, 0.909804, 0.752941),  # 26  #92e8c0
	Color(1.0, 1.0, 1.0),  # 27  #ffffff
	Color(0.639216, 0.654902, 0.760784),  # 28  #a3a7c2
	Color(0.407843, 0.435294, 0.6),  # 29  #686f99
	Color(0.270588, 0.290196, 0.415686),  # 30  #454a6a
	Color(0.113725, 0.133333, 0.207843),  # 31  #1d2235
]

## Ramps, each ordered dark -> light. Shade within a ramp; a cat drawn
## from WARM and one drawn from COOL will still look related.
const WARM: Array[Color] = [COLORS[0], COLORS[1], COLORS[2], COLORS[3], COLORS[4], COLORS[5], COLORS[6], COLORS[7], COLORS[8]]
const BERRY: Array[Color] = [COLORS[10], COLORS[11], COLORS[12], COLORS[13], COLORS[14]]
const GOLD: Array[Color] = [COLORS[14], COLORS[15], COLORS[16], COLORS[17]]
const GREEN: Array[Color] = [COLORS[21], COLORS[20], COLORS[19], COLORS[18]]
const TEAL: Array[Color] = [COLORS[22], COLORS[23], COLORS[24], COLORS[25], COLORS[26]]
const COOL: Array[Color] = [COLORS[31], COLORS[30], COLORS[29], COLORS[28], COLORS[27]]

const PINK := COLORS[9]
const WHITE := COLORS[27]
const TEXT := COLORS[27]
const TEXT_DIM := COLORS[28]
const PANEL := COLORS[30]
const PANEL_DARK := COLORS[31]
const SHADOW := COLORS[0]
const COIN := COLORS[16]
const GOOD := COLORS[20]
const WARN := COLORS[15]
const BAD := COLORS[13]
