"""Generate palette-derived assets from assets/palette/aren32.hex.

Regenerates:
  scripts/palette.gd                     -- named colours and ramps for code
  assets/palette/aren32_swatch.png       -- visual reference sheet
  assets/room/tiles_placeholder.png      -- placeholder floor/wall tiles

Run after changing the palette:  python tools/gen_palette.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
HEX_FILE = ROOT / "assets" / "palette" / "aren32.hex"
TILE = 32

# Ramps, each ordered dark -> light. Indices into the palette file's order.
RAMPS = {
    "WARM": [0, 1, 2, 3, 4, 5, 6, 7, 8],
    "BERRY": [10, 11, 12, 13, 14],
    "GOLD": [14, 15, 16, 17],
    "GREEN": [21, 20, 19, 18],
    "TEAL": [22, 23, 24, 25, 26],
    "COOL": [31, 30, 29, 28, 27],
}

# Single colours worth naming, because code reads better than an index.
NAMED = {
    "PINK": 9,
    "WHITE": 27,
    "TEXT": 27,
    "TEXT_DIM": 28,
    "PANEL": 30,
    "PANEL_DARK": 31,
    "SHADOW": 0,
    "COIN": 16,
    "GOOD": 20,
    "WARN": 15,
    "BAD": 13,
}

# Placeholder tiles: (name, fill index, edge index).
# Floor sits low on the WARM ramp and walls on COOL: a darker warm floor recedes,
# lets a bright cat read against it, and keeps the room from going orange.
TILES = [
    ("floor_a", 6, 5),
    ("floor_b", 5, 4),
    ("wall", 28, 29),
    ("wall_top", 29, 30),
]


def load_palette() -> list[tuple[int, int, int]]:
    colors = []
    for line in HEX_FILE.read_text().splitlines():
        line = line.strip().lstrip("#")
        if not line or line.startswith(";"):
            continue
        colors.append((int(line[0:2], 16), int(line[2:4], 16), int(line[4:6], 16)))
    return colors


def write_tiles(pal):
    img = Image.new("RGBA", (TILE * len(TILES), TILE), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    for i, (_name, fill, edge) in enumerate(TILES):
        x0 = i * TILE
        draw.rectangle([x0, 0, x0 + TILE - 1, TILE - 1], fill=pal[fill])
        # 1px darker bottom+right edge keeps the grid readable while blocking out.
        draw.line([(x0, TILE - 1), (x0 + TILE - 1, TILE - 1)], fill=pal[edge])
        draw.line([(x0 + TILE - 1, 0), (x0 + TILE - 1, TILE - 1)], fill=pal[edge])
    out = ROOT / "assets" / "room" / "tiles_placeholder.png"
    img.save(out)
    print(f"wrote {out.relative_to(ROOT)} ({img.width}x{img.height})")


def write_swatch(pal, cell=48, cols=8):
    rows = (len(pal) + cols - 1) // cols
    img = Image.new("RGBA", (cols * cell, rows * cell), (0, 0, 0, 255))
    draw = ImageDraw.Draw(img)
    for i, rgb in enumerate(pal):
        x0, y0 = (i % cols) * cell, (i // cols) * cell
        draw.rectangle([x0, y0, x0 + cell - 1, y0 + cell - 1], fill=rgb)
        label = f"{i}"
        # Contrasting label so the index is readable on light and dark swatches.
        ink = (0, 0, 0) if sum(rgb) > 380 else (255, 255, 255)
        draw.text((x0 + 3, y0 + 2), label, fill=ink)
    out = ROOT / "assets" / "palette" / "aren32_swatch.png"
    img.save(out)
    print(f"wrote {out.relative_to(ROOT)} ({img.width}x{img.height})")


def gd_color(rgb) -> str:
    r, g, b = (round(c / 255.0, 6) for c in rgb)
    return f"Color({r}, {g}, {b})"


def write_gdscript(pal):
    lines = [
        "class_name Palette",
        "## Aren32 -- https://lospec.com/palette-list/aren32",
        "##",
        "## GENERATED by tools/gen_palette.py from assets/palette/aren32.hex.",
        "## Do not edit by hand; edit the .hex and re-run the generator.",
        "##",
        "## Every colour drawn in code comes from here. Sticking to one palette is",
        "## what makes hand-drawn art and downloaded assets look like one game.",
        "",
        "const COLORS: Array[Color] = [",
    ]
    for i, rgb in enumerate(pal):
        lines.append(f"\t{gd_color(rgb)},  # {i:>2}  #{'%02x%02x%02x' % rgb}")
    lines.append("]")
    lines.append("")
    lines.append("## Ramps, each ordered dark -> light. Shade within a ramp; a cat drawn")
    lines.append("## from WARM and one drawn from COOL will still look related.")
    for name, idx in RAMPS.items():
        body = ", ".join(f"COLORS[{i}]" for i in idx)
        lines.append(f"const {name}: Array[Color] = [{body}]")
    lines.append("")
    for name, i in NAMED.items():
        lines.append(f"const {name} := COLORS[{i}]")
    out = ROOT / "scripts" / "palette.gd"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)} ({len(pal)} colours)")


if __name__ == "__main__":
    palette = load_palette()
    assert len(palette) == 32, f"expected 32 colours, found {len(palette)}"
    write_gdscript(palette)
    write_swatch(palette)
    write_tiles(palette)
